### ISSUE TITLE
Cannot find config.py

### ISSUE THREAD

**Issue by jenniferzhu** [dbs/postgresql-full-text-search-engine#1]
In "Modify the constants in initialize, restapp/config.py, and webapp/config.py to reflect the required PostgreSQL connection information.", what do you actually mean? Where are those config.py files?

**Comment by dbs** [comment]
Ah, looks like I had either planned to refactor the constants out of webapp/webserv and restapp/restserv into separate config.py files, or thought better of it and decided to just let people edit those files directly. For now, just edit the files directly; I'll either update the docs, or separate out the config.py files accordingly.
